### ISSUE TITLE
Missing framework headers in 2.1 when using CocoaPods

### ISSUE THREAD

**Issue by danteppc** [chabok-io/chabok-client-ios#1]
Hey,

Framework headers are missing when poding the last version (2.1), There's no way to import the module, leaving us no choice but to explicitly use the prior version (i.e. 2.0.1) or not use the pod at all.
![Screen Shot 2019-12-30 at 10 51 33 AM](https://user-images.githubusercontent.com/15725082/71572019-77e26780-2af2-11ea-8785-288c0dc7790c.png)

**Comment by farbod-s** [comment]
<div dir="ltr">
hi @danteppc
<br>
please clean your cocoapod local cache and try to install ChabokPush v2.1.0 again.
</div>

```bash
pod cache clean ChabokPush --all
pod repo update
pod install
```
