### ISSUE TITLE
Problem with NSNull in data

### ISSUE THREAD

**Issue by danteppc** [chabok-io/chabok-client-ios#2]
Hey,

The framework crashes when assigning NSNull for nil values in the `track:data:` method.

`[PushClientManager.defaultManager track:@"event" data: @{@"key":[NSNull null]}];`

![Screen Shot 2020-02-05 at 11 34 24 AM](https://user-images.githubusercontent.com/15725082/73822484-7734a380-480b-11ea-8ab2-f819c488d781.png)

**Comment by farbod-s** [comment]
hi, @danteppc 
please don't send null values for event data.
consider that you can send an event without data but if you put data for your event you must avoid null values for event data.

**Comment by danteppc** [comment]
NSNull is a recognized “null” value typically used in JSON serialization. It’s not a null pointer so it’s best that you treat it adequately.

**Comment by farbod-s** [comment]
what does null value mean for you in event data?
simply if you don't put null values in event data it means that value does not exist for the event data.
processing null values have overhead for us, so we ignore to check them. (consider nested values in your data)

**Comment by danteppc** [comment]
I’ve already worked out a fix, the point was a crash report.
Thanks anyway
